widgetParams:
  -
    name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'SURI_PROJECT_KEY'
    description: 'Project key'
    type: TEXT
    usageExample: 'com.project.key:ProjectName'
    required: true
  -
    name: 'SURI_METRICS'
    description: 'Metrics to display'
    type: MULTIPLE
    possibleValuesMap:
      -
        jsKey: 'new_line_coverage'
        value: 'Lines coverage'
      -
        jsKey: 'new_lines_to_cover'
        value: 'Lines to cover'
      -
        jsKey: 'new_uncovered_lines'
        value: 'Uncovered lines'
      -
        jsKey: 'new_coverage'
        value: 'Coverage on new code(%)'
      -
        jsKey: 'new_conditions_to_cover'
        value: 'Conditions to cover'
      -
        jsKey: 'new_uncovered_conditions'
        value: 'Unconver conditions'
    required: true
  -
    name: 'SURI_BRANCH'
    description: 'Branch name, if user provides both branch and pull request, the branch takes precedence.'
    type: TEXT
    usageExample: 'My branch'
    required: false
  -
    name: 'SURI_PULL_REQUEST'
    description: 'Merge/Pull Request Number'
    type: TEXT
    usageExample: '111'
    required: false