widgetParams:
  -
    name: 'WIDGET_PROJECT_IDS_OR_PATHS'
    description: 'Project IDs or paths (comma-separated)'
    type: 'TEXT'
    usageExample: '123456,my-group/my-project'
    required: true
  -
    name: 'WIDGET_PERIOD_UNIT'
    description: 'Unit of period'
    type: 'COMBO'
    possibleValuesMap:
      - jsKey: 'year'
        value: 'Year'
      - jsKey: 'month'
        value: 'Month'
      - jsKey: 'week'
        value: 'Week'
    required: false
  -
    name: 'WIDGET_PERIOD_NUMBER'
    description: 'Number of periods'
    type: 'NUMBER'
    usageExample: '1'
    required: false