widgetParams:
  -
    name: 'SURI_MARKDOWN'
    description: 'Upload a markdown file'
    type: FILE
    acceptFileRegex: '^data:application\/octet-stream;base64,.+$'
    required: true
  -
    name: 'SURI_WIDGET_COLOR'
    description: 'Background color'
    type: TEXT
    usageExample: '#AB4040'
    required: false