widgetParams:
  - name: 'WIDGET_TITLE'
    description: 'Widget title'
    type: 'TEXT'
    usageExample: 'My title'
    required: true
  - name: 'WIDGET_JQL'
    description: 'JQL query to count the issues'
    type: 'TEXT'
    usageExample: 'project = XXXX'
    required: true
  - name: 'WIDGET_DELAY'
    description: 'Duration used to measure the change rate from previous executions (in hours)'
    type: 'NUMBER'
    defaultValue: '24'
    required: true