widgetParams:
  -
    name: WIDGET_PROJECT_ID_OR_PATH
    description: 'Project ID or path'
    type: TEXT
    usageExample: 'my-group/my-project'
    required: true
  -
    name: WIDGET_BRANCH
    description: 'Use a specific branch'
    type: TEXT
    usageExample: 'master'
    required: false
  -
    name: WIDGET_HIDE_TIMETABLE
    description: 'Hide timetable (duration and queue time)'
    type: BOOLEAN
    defaultValue: false
    required: false
  -
    name: WIDGET_SHOW_FAILED_JOBS
    description: 'Show failed jobs'
    type: BOOLEAN
    defaultValue: false
    required: false
