widgetParams:
  - name: 'WIDGET_TITLE'
    description: 'Widget title'
    type: 'TEXT'
    usageExample: 'My title'
    required: true
  - name: 'WIDGET_JQL'
    description: 'JQL query to list the issues'
    type: 'TEXT'
    usageExample: 'project = XXX'
    required: true
  - name: 'WIDGET_NUMBER'
    description: 'Number of issues to display'
    type: 'NUMBER'
    defaultValue: '5'
    required: true
  - name: 'WIDGET_DISPLAY_JIRA_ID'
    description: 'Display the identifier of the Jira issue'
    type: 'BOOLEAN'
    defaultValue: 'false'
    required: false