widgetParams:
  -
    name: 'WIDGET_GITHUB_ORGANIZATION'
    description: 'GitHub organization'
    type: TEXT
    required: true
  -
    name: 'WIDGET_GITHUB_PROJECT'
    description: 'GitHub project'
    type: TEXT
    required: true
  -
    name: 'WIDGET_GITHUB_ISSUES_STATE'
    description: 'Filter on the state of the issues'
    type: COMBO
    defaultValue: 'all'
    possibleValuesMap:
      -
        jsKey: all
        value: All
      -
        jsKey: open
        value: Open
      -
        jsKey: closed
        value: Closed
    required: true
