widgetParams:
  -
    name: SURI_PROJECT
    description: 'Project ID'
    type: TEXT
    usageExample: '1234'
    required: true
  -
    name: 'SURI_ISSUES_STATE'
    description: 'Filter on the state of the issues'
    type: COMBO
    defaultValue: 'all'
    possibleValuesMap:
      -
        jsKey: all
        value: All
      -
        jsKey: opened
        value: Opened
      -
        jsKey: closed
        value: Closed
    required: true
