widgetParams:
  - name: 'SURI_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  - name: 'SURI_RUNNER_TAG'
    description: 'Filter on a runner tag'
    type: TEXT
    usageExample: 'kso'
    required: true
