widgetParams:
  - name: 'SURI_PROJECT'
    description: 'Project name'
    type: TEXT
    usageExample: 'ProjectName1'
    required: true
  - name: 'SURI_PROJECT_VERSION'
    description: 'Project version'
    type: TEXT
    usageExample: 'master-2.5.0'
    required: true
  - name: 'SURI_PERIOD'
    description: 'Retrieve the analyzes from a period'
    type: COMBO
    defaultValue: 'Month'
    possibleValuesMap:
      - jsKey: Year
        value: Year
      - jsKey: Month
        value: Month
      - jsKey: Week
        value: Week
      - jsKey: Day
        value: Day
    required: false
  - name: 'SURI_NUMBER_OF_PERIOD'
    description: 'Unit of the selected period'
    type: NUMBER
    usageExample: 1
    defaultValue: 6
    required: false
