widgetParams:
  -
    name: 'WIDGET_TITLE'
    description: 'Widget title'
    type: 'TEXT'
    usageExample: 'My title'
    required: true
  -
    name: 'WIDGET_NAMESPACE'
    description: 'Namespace of the pods'
    type: 'TEXT'
    usageExample: 'namespace'
    required: true
  -
    name: 'WIDGET_SERVICE_ACCOUNT_TOKEN'
    description: 'Namespace token (e.g. service account token, Gitlab token, ...)'
    type: 'PASSWORD'
    usageExample: 'eyJhbGciOiJSU'
    required: true
  -
    name: 'WIDGET_ORDER_BY'
    description: 'Order the pods by'
    type: 'COMBO'
    defaultValue: 'START_DATE_DESC'
    possibleValuesMap:
      -
        jsKey: 'START_DATE_ASC'
        value: 'Oldest pods first'
      -
        jsKey: 'START_DATE_DESC'
        value: 'Newest pods first'
    required: true
  -
    name: 'WIDGET_TOP'
    description: 'Number of pods to display. All by default'
    type: 'NUMBER'
    usageExample: '3'
    required: false
  -
    name: 'WIDGET_STATUS'
    description: 'Filter by status of the pods'
    type: 'COMBO'
    defaultValue: 'All'
    possibleValuesMap:
      -
        jsKey: 'All'
        value: 'All'
      -
        jsKey: 'Running'
        value: 'Running'
      -
        jsKey: 'Pending'
        value: 'Pending'
      -
        jsKey: 'Succeeded'
        value: 'Succeeded'
      -
        jsKey: 'Failed'
        value: 'Failed'
      -
        jsKey: 'Unknown'
        value: 'Unknown'
    required: true
  -
    name: 'WIDGET_PODS_NAME'
    description: 'Filter on the name of the pods. Substring accepted'
    type: 'TEXT'
    usageExample: 'frontend'
    required: false