widgetParams:
  -
    name: 'WIDGET_TITLE'
    description: 'Widget title'
    type: TEXT
    usageExample: 'My title'
    required: true
  -
    name: 'WIDGET_PROJECT_KEY'
    description: 'Projects names (substring accepted) or projects keys (full match only), separated by a comma'
    type: TEXT
    usageExample: 'ProjectName1,com.project2.key:ProjectName2,ProjectName3'
    required: true
  -
    name: 'WIDGET_PERIOD_UNIT'
    description: 'Retrieve the analyses from a period'
    type: COMBO
    possibleValuesMap:
      -
        jsKey: Year
        value: Year
      -
        jsKey: Month
        value: Month
      -
        jsKey: Week
        value: Week
      -
        jsKey: Day
        value: Day
    required: false
  -
    name: 'WIDGET_PERIOD_NUMBER'
    description: 'Unit of the selected period'
    type: NUMBER
    usageExample: 1
    required: false
  -
    name: 'WIDGET_CHART_TYPE'
    description: 'Chart type'
    type: 'COMBO'
    defaultValue: 'bar'
    possibleValuesMap:
      -
        jsKey: 'pie'
        value: 'Pie'
      -
        jsKey: 'horizontalBar'
        value: 'Horizontal bar'
      -
        jsKey: 'bar'
        value: 'Vertical bar'
