widgetParams:
  - name: 'WIDGET_IMG'
    description: 'Image #1'
    type: 'FILE'
    acceptFileRegex: '^data:image\/(gif|jpe?g|png);base64,.+$'
    required: true
  - name: 'WIDGET_IMG_2'
    description: 'Image #2'
    type: 'FILE'
    acceptFileRegex: '^data:image\/(gif|jpe?g|png);base64,.+$'
    required: false
  - name: 'WIDGET_IMG_3'
    description: 'Image #3'
    type: 'FILE'
    acceptFileRegex: '^data:image\/(gif|jpe?g|png);base64,.+$'
    required: false
  - name: 'WIDGET_IMG_4'
    description: 'Image #4'
    type: 'FILE'
    acceptFileRegex: '^data:image\/(gif|jpe?g|png);base64,.+$'
    required: false
  - name: 'WIDGET_IMG_5'
    description: 'Image #5'
    type: 'FILE'
    acceptFileRegex: '^data:image\/(gif|jpe?g|png);base64,.+$'
    required: false