widgetParams:
  - name: 'WIDGET_TITLE'
    description: 'Widget title'
    type: 'TEXT'
    usageExample: 'My title'
    required: false
  - name: 'WIDGET_TEXT'
    description: 'Widget text'
    type: 'TEXTAREA'
    usageExample: 'My content'
    required: false
  - name: 'WIDGET_TITLE_SIZE'
    description: 'Title size'
    type: 'COMBO'
    defaultValue: 'small'
    possibleValuesMap:
      - jsKey: 'small'
        value: 'Small'
      - jsKey: 'medium'
        value: 'Medium'
      - jsKey: 'large'
        value: 'Large'
      - jsKey: 'very-large'
        value: 'Very large'
    required: true
  - name: 'WIDGET_TEXT_SIZE'
    description: 'Text size'
    type: 'COMBO'
    defaultValue: 'small'
    possibleValuesMap:
      - jsKey: 'small'
        value: 'Small'
      - jsKey: 'medium'
        value: 'Medium'
      - jsKey: 'large'
        value: 'Large'
      - jsKey: 'very-large'
        value: 'Very large'
    required: true